USE WEATHER_DW;
GO

CREATE TABLE DIM_LOCATION(
	LOCATION_KEY INT IDENTITY(1,1) PRIMARY KEY,
	[NAME] NVARCHAR(255)
);
GO

CREATE TABLE DIM_WIND (
	WIND_KEY INT IDENTITY(1,1) PRIMARY KEY,
	--SPEED INT,
	DIRECTION NVARCHAR(50)
);
GO

CREATE TABLE DIM_DATE (
	DATE_KEY INT IDENTITY(1,1) PRIMARY KEY,
	[DAY] INT,
	[MONTH] INT,
	[YEAR] INT,
	SEASON INT
);
GO 

SELECT * FROM dbo.DIM_DATE;
SELECT * FROM dbo.DIM_LOCATION;
SELECT * FROM dbo.DIM_WIND;
SELECT * FROM dbo.[FACT TABLE];
GO

TRUNCATE TABLE dbo.DIM_DATE;
TRUNCATE TABLE dbo.DIM_LOCATION;
TRUNCATE TABLE dbo.DIM_WIND;
TRUNCATE TABLE dbo.[FACT TABLE];
GO

-- Thêm khóa ngoại cho LOCATION_KEY từ DIM_LOCATION
ALTER TABLE FACT
ADD CONSTRAINT FK_WEATHER_LOCATION FOREIGN KEY (LOCATION_KEY) REFERENCES DIM_LOCATION(LOCATION_KEY);

-- Thêm khóa ngoại cho WIND_KEY từ DIM_WIND
ALTER TABLE FACT
ADD CONSTRAINT FK_WEATHER_WIND FOREIGN KEY (WIND_KEY) REFERENCES DIM_WIND(WIND_KEY);

-- Thêm khóa ngoại cho DATE_KEY từ DIM_DATE
ALTER TABLE FACT
ADD CONSTRAINT FK_WEATHER_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY);


