USE WEATHER_DW;
GO

CREATE TABLE DIM_LOCATION(
	LOCATION_KEY INT IDENTITY(1,1) PRIMARY KEY,
	[NAME] NVARCHAR(255)
);
GO

CREATE TABLE DIM_WIND (
	WIND_KEY INT IDENTITY(1,1) PRIMARY KEY,
	SPEED INT,
	DIRECTION NVARCHAR(50)
);
GO

CREATE TABLE DIM_DATE (
	DATE_KEY INT IDENTITY(1,1) PRIMARY KEY,
	[DAY] INT,
	[MONTH] INT,
	[YEAR] INT,
	SEASON INT
);
GO 

SELECT * FROM dbo.DIM_DATE;
SELECT * FROM dbo.DIM_LOCATION;
SELECT * FROM dbo.DIM_WIND;
SELECT * FROM dbo.FACT;
GO

TRUNCATE TABLE dbo.DIM_DATE;
TRUNCATE TABLE dbo.DIM_LOCATION;
TRUNCATE TABLE dbo.DIM_WIND;
TRUNCATE TABLE dbo.FACT;
GO



